image: python:3.9.14-bullseye

stages:
  - Static Analysis
  - Test
  - Documentation
  - Release

before_script:
  - python --version
  - pip install --upgrade pip setuptools
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install ".[test, doc, dev]"

linting:
  stage: Static Analysis
  script:
    - pylint src/sofirpy

type_checking:
  stage: Static Analysis
  script:
    - mypy src/sofirpy

test:
  stage: Test
  script:
    - pytest tests/

doc:
  stage: Documentation
  script:
    - cd docs/
    - make html

release:
  stage: Release
  only:
    - tags
  script:
    - tag_version=`echo "$CI_COMMIT_TAG"|cut -d "v" -f2`
    - ver=`pip show sofirpy|grep Version|cut -d " " -f2`
    - echo $ver
    - echo $tag_version
    - >
      if [ "$tag_version" != "$ver" ]
      then
        echo "GitLab TAG "$tag_version" does not match specified version "$ver" in sofirpy/__init__.py"
        exit 1
      fi
    - echo "versions match"