image: python:latest

stages: 
  - test


before_script:
  - python --version
  - pip install --upgrade pip setuptools
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .[test]

static_anaysis:
  stage: test
  script:
    - mypy src/sofirpy

test:
  stage: test
  script:
    - pytest tests/
