image: python:latest

stages: 
  - build
  - static-analysis
  - test


before_script:
  - python --version
  - pip install --upgrade pip setuptools
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

install_project:
  stage: build
  script:
    - pip install . [test]

static_anaysis:
  stage: static-analysis
  script:
    - mypy src/sofirpy

test:
  stage: test
  script:
    - pytest tests/
