[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
show_error_codes = true
warn_unused_ignores = true
[[tool.mypy.overrides]]
module = [
    "fmpy",
    "fmpy.fmi2",
    "h5py",
    "matplotlib",
    "matplotlib.axes",
    "matplotlib.pyplot",
    "OMPython"

]
ignore_missing_imports = true
